// Come, Follow Me 2026 — Old Testament
// QUICK REFERENCE ONLY: date range, scripture block, one-line theme.
// (Condensed from the full Covenant Path dataset — no summaries/highlights/questions here.)

const CFM_2026 = [
  { id: 1,  dates: "Dec 29–Jan 4",  ref: "Introduction to the Old Testament", theme: "Why this record matters and how to read it well this year" },
  { id: 2,  dates: "Jan 5–11",      ref: "Moses 1; Genesis 1–2",              theme: "The Creation — all things bear record of God" },
  { id: 3,  dates: "Jan 12–18",     ref: "Moses 2–4; Genesis 3",              theme: "Agency, the Fall, and opposition in all things" },
  { id: 4,  dates: "Jan 19–25",     ref: "Moses 5–7; Genesis 4–5",            theme: "Cain and Abel; the pattern of the pride cycle begins" },
  { id: 5,  dates: "Jan 26–Feb 1",  ref: "Moses 8; Genesis 6–11",             theme: "Noah, the Flood, and covenant obedience amid corruption" },
  { id: 6,  dates: "Feb 2–8",       ref: "Abraham 1–2; Genesis 12–17",        theme: "Abraham's covenant — faith that becomes a legacy" },
  { id: 7,  dates: "Feb 9–15",      ref: "Genesis 18–23",                     theme: "Sodom, Isaac's birth, and the testing of faith" },
  { id: 8,  dates: "Feb 16–22",     ref: "Genesis 24–27",                     theme: "Isaac and Rebekah; birthright and blessing" },
  { id: 9,  dates: "Feb 23–Mar 1",  ref: "Genesis 28–33",                     theme: "Jacob's ladder and wrestle; reconciliation with Esau" },
  { id: 10, dates: "Mar 2–8",       ref: "Genesis 37–41",                     theme: "Joseph sold into Egypt — providence in adversity" },
  { id: 11, dates: "Mar 9–15",      ref: "Genesis 42–50",                     theme: "Joseph forgives his brothers; family preserved" },
  { id: 12, dates: "Mar 16–22",     ref: "Job 1–3; 12–14; 19; 21–24; 38–42",   theme: "Job's integrity in suffering" },
  { id: 13, dates: "Mar 23–29",     ref: "Exodus 1–6",                        theme: "Moses called at the burning bush" },
  { id: 14, dates: "Mar 30–Apr 5",  ref: "Exodus 7–13",                       theme: "The plagues and the Passover" },
  { id: 15, dates: "Apr 6–12",      ref: "Exodus 14–17; 33",                  theme: "Deliverance through the Red Sea" },
  { id: 16, dates: "Apr 13–19",     ref: "Exodus 18–20",                      theme: "The Ten Commandments at Sinai" },
  { id: 17, dates: "Apr 20–26",     ref: "Exodus 24; 31–34; 35–40",           theme: "The tabernacle — a portable temple" },
  { id: 18, dates: "Apr 27–May 3",  ref: "Leviticus 1; 16; 19",               theme: "Holiness and the law of sacrifice as a type of Christ" },
  { id: 19, dates: "May 4–10",      ref: "Numbers 11–14; 20–24",              theme: "Murmuring, the spies, and Balaam" },
  { id: 20, dates: "May 11–17",     ref: "Deuteronomy 6–8; 11; 29–30; 34",    theme: "Choose this day whom you will serve" },
  { id: 21, dates: "May 18–24",     ref: "Joshua 1–8; 23–24",                 theme: "Be strong and of a good courage" },
  { id: 22, dates: "May 25–31",     ref: "Judges 2; 4; 6–7; 13–16",           theme: "The cycle of deliverance — judges raised up" },
  { id: 23, dates: "Jun 1–7",       ref: "Ruth 1–4",                          theme: "Loyalty and redemption; Ruth's covenant choice" },
  { id: 24, dates: "Jun 8–14",      ref: "1 Samuel 1–3; 8; 9–11; 13",         theme: "Samuel called; Israel asks for a king" },
  { id: 25, dates: "Jun 15–21",     ref: "1 Samuel 15–18",                    theme: "David anointed; David and Goliath" },
  { id: 26, dates: "Jun 22–28",     ref: "1 Samuel 19–24; 31",                theme: "David spares Saul; integrity under threat" },
  { id: 27, dates: "Jun 29–Jul 5",  ref: "2 Samuel 5–7; 11–12",               theme: "David as king; his fall and Nathan's rebuke" },
  { id: 28, dates: "Jul 6–12",      ref: "1 Kings 3; 5–11",                   theme: "Solomon's wisdom and the temple's dedication" },
  { id: 29, dates: "Jul 13–19",     ref: "1 Kings 12–14; 17–19",              theme: "The kingdom divides; Elijah at Carmel and Horeb" },
  { id: 30, dates: "Jul 20–26",     ref: "2 Kings 2; 5–6",                    theme: "Elijah taken up; Elisha's miracles" },
  { id: 31, dates: "Jul 27–Aug 2",  ref: "2 Kings 17–25",                     theme: "The fall of Israel and Judah" },
  { id: 32, dates: "Aug 3–9",       ref: "Selections from 1–2 Chronicles",    theme: "A second witness of the kings' history" },
  { id: 33, dates: "Aug 10–16",     ref: "Ezra 1; 3–7; Nehemiah 2; 4; 6; 8",   theme: "Return from exile; rebuilding the temple and walls" },
  { id: 34, dates: "Aug 17–23",     ref: "Esther 1–10",                      theme: "Courage to act — 'if I perish, I perish'" },
  { id: 35, dates: "Aug 24–30",     ref: "Proverbs 1–4; 15–16; 22; 31",       theme: "Wisdom literature for daily living" },
  { id: 36, dates: "Aug 31–Sep 6",  ref: "Ecclesiastes 1–3; 11–12",           theme: "Vanity, meaning, and remembering your Creator" },
  { id: 37, dates: "Sep 7–13",      ref: "Song of Solomon (optional/selections)", theme: "Covenant love as poetry" },
  { id: 38, dates: "Sep 14–20",     ref: "Isaiah 1–6; 7–12",                  theme: "Isaiah's call; Immanuel prophecies" },
  { id: 39, dates: "Sep 21–27",     ref: "Isaiah 40–49",                      theme: "Comfort, the Suffering Servant foreshadowed" },
  { id: 40, dates: "Sep 28–Oct 4",  ref: "Isaiah 50–53; 61",                  theme: "He was wounded for our transgressions" },
  { id: 41, dates: "Oct 5–11",      ref: "Jeremiah 1–2; 15; 20; 29; 31",      theme: "Jeremiah's call and the new covenant promise" },
  { id: 42, dates: "Oct 12–18",     ref: "Ezekiel 1–3; 18; 34; 37",           theme: "Dry bones, the good shepherd, individual accountability" },
  { id: 43, dates: "Oct 19–25",     ref: "Daniel 1–6",                       theme: "Faith tested — the furnace and the lions' den" },
  { id: 44, dates: "Oct 26–Nov 1",  ref: "Hosea 1–3; 11; 13–14",              theme: "God's covenant love compared to a faithful marriage" },
  { id: 45, dates: "Nov 2–8",       ref: "Joel; Amos",                        theme: "Pour out my spirit; let justice run as waters" },
  { id: 46, dates: "Nov 9–15",      ref: "Jonah; Micah",                     theme: "Mercy for Nineveh; do justly, love mercy, walk humbly" },
  { id: 47, dates: "Nov 16–22",     ref: "Nahum; Habakkuk; Zephaniah",        theme: "Faith though the fig tree shall not blossom" },
  { id: 48, dates: "Nov 23–29",     ref: "Haggai; Zechariah",                 theme: "Rebuilding priorities; messianic prophecy" },
  { id: 49, dates: "Nov 30–Dec 6",  ref: "Malachi 1–4",                      theme: "Turning hearts; the promise of Elijah's return" },
  { id: 50, dates: "Dec 7–13",      ref: "Old Testament Overview",            theme: "Tying the year's themes together" },
  { id: 51, dates: "Dec 14–20",     ref: "Luke 1; Matthew 1–2",               theme: "The Christmas story begins the next testament" },
  { id: 52, dates: "Dec 21–27",     ref: "Luke 2; Matthew 2",                 theme: "Christmas — the Word made flesh" }
];

// LDS Books shelf — seed empty, app adds via UI
const SEED_BOOKS = [];
